# Generated by Django 3.2.13 on 2022-06-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('content_id', models.CharField(db_index=True, max_length=255)),
                ('exam_name', models.TextField()),
                ('exam_type', models.CharField(db_index=True, max_length=255)),
                ('time_limit_mins', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(null=True)),
                ('hide_after_due', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'exam',
                'db_table': 'exams_exam',
            },
        ),
        migrations.CreateModel(
            name='ProctoringProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('verbose_name', models.CharField(db_index=True, max_length=255)),
                ('lti_configuration_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'proctoring provider',
                'db_table': 'exams_proctoringprovider',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='anonymous_user_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(null=True)),
                ('allowed_time_limit_mins', models.IntegerField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exam attempt',
                'db_table': 'exams_examattempt',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proctoringprovider'),
        ),
        migrations.CreateModel(
            name='CourseExamConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('allow_opt_out', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proctoringprovider')),
            ],
            options={
                'verbose_name': 'course exam configuration',
                'db_table': 'exams_courseexamconfiguration',
            },
        ),
    ]
