# Generated by Django 3.2.13 on 2022-06-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_exam_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('proctored', 'Non-practice, timed, proctored exam'), ('timed', 'Non-practice, non-proctored, timed exam')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proctoringprovider'),
        ),
    ]
