# Generated by Django 3.2.13 on 2022-06-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_allow_null_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('course_id', 'content_id', 'exam_type', 'provider')},
        ),
    ]
