# Generated by Django 3.2.14 on 2022-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_lms_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamconfiguration',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
