# Generated by Django 3.2.14 on 2022-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_allow_null_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('proctored', 'Non-practice, proctored, timed exam'), ('timed', 'Non-practice, non-proctored, timed exam'), ('practice', 'Practice, non-proctored, timed exam'), ('onboarding', 'Practice, proctored, timed exam')], db_index=True, max_length=255),
        ),
    ]
