# Generated by Django 3.2.14 on 2022-09-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamconfiguration',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proctoringprovider'),
        ),
    ]
