# Generated by Django 3.2.15 on 2022-09-29 20:54

from django.db import migrations, models
import uuid


def create_anonymous_user_ids(apps, schema_editor):
    User = apps.get_model('core', 'User')
    users = User.objects.all()
    for user in users:
        user.anonymous_user_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_anonymous_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymous_user_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(create_anonymous_user_ids),
        migrations.AlterField(
            model_name='user',
            name='anonymous_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
