# Generated by Django 3.2.16 on 2023-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_exam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('proctored', 'proctored'), ('timed', 'timed'), ('practice', 'practice'), ('onboarding', 'onboarding')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('download_software_clicked', 'download_software_clicked'), ('ready_to_start', 'ready_to_start'), ('started', 'started'), ('ready_to_submit', 'ready_to_submit'), ('timed_out', 'timed_out'), ('submitted', 'submitted'), ('verified', 'verified'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=64),
        ),
    ]
