# Generated by Django 3.2.18 on 2023-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalexam_historicalexamattempt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course_id', 'content_id'), name='only one exam instance active'),
        ),
    ]
