# Generated by Django 3.2.18 on 2023-07-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_provider_contact_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentControlResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action_type', models.CharField(choices=[('terminate', 'terminate')], max_length=64)),
                ('incident_time', models.DateTimeField()),
                ('severity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reason_code', models.CharField(max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examattempt')),
            ],
            options={
                'verbose_name': 'assessment control result',
                'db_table': 'exams_assessmentcontrolresult',
            },
        ),
    ]
