# Generated by Django 3.2.20 on 2023-08-14 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_assessmentcontrolresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('download_software_clicked', 'download_software_clicked'), ('ready_to_start', 'ready_to_start'), ('started', 'started'), ('ready_to_submit', 'ready_to_submit'), ('timed_out', 'timed_out'), ('submitted', 'submitted'), ('verified', 'verified'), ('rejected', 'rejected'), ('expired', 'expired'), ('second_review_required', 'second_review_required'), ('error', 'error')], max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalexamattempt',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('download_software_clicked', 'download_software_clicked'), ('ready_to_start', 'ready_to_start'), ('started', 'started'), ('ready_to_submit', 'ready_to_submit'), ('timed_out', 'timed_out'), ('submitted', 'submitted'), ('verified', 'verified'), ('rejected', 'rejected'), ('expired', 'expired'), ('second_review_required', 'second_review_required'), ('error', 'error')], max_length=64),
        ),
        migrations.CreateModel(
            name='CourseStaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course staff role',
                'db_table': 'exams_coursestaffrole',
            },
        ),
    ]
