# Generated by Django 3.2.21 on 2023-10-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staff_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name'),
        ),
    ]
