# Generated by Django 3.2.22 on 2023-10-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalexam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical exam', 'verbose_name_plural': 'historical exams'},
        ),
        migrations.AlterModelOptions(
            name='historicalexamattempt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical exam attempt', 'verbose_name_plural': 'historical exam attempts'},
        ),
    ]
