# Generated by Django 3.2.23 on 2023-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_exam_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexamconfiguration',
            name='escalation_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
