# Generated by Django 3.2.23 on 2023-12-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_courseexamconfiguration_escalation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringprovider',
            name='tech_support_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
