# Generated by Django 3.2.23 on 2024-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_proctoringprovider_tech_support_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestaffrole',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
