# Generated by Django 4.2.11 on 2024-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_coursestaffrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringprovider',
            name='org_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
