# Generated by Django 4.2.14 on 2024-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_studentallowance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursestaffrole',
            constraint=models.UniqueConstraint(fields=('user', 'course_id', 'role'), name='unique_course_staff_role'),
        ),
    ]
